version: '3.2'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
      - ./proxies.json:/datastore/proxies.json

    environment:
      - PORT=5000
      - LOGGER_LEVEL=TRACE
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
      - HTTP_PROXY=socks5h://10.10.1.10:1080
      - HTTPS_PROXY=socks5h://10.10.1.10:1080
      - NO_PROXY=localhost,192.168.0.0/24
      - BASE_URL=https://mysite.com
      - USE_X_SETTINGS=1
      - HIDE_REFERER=true
      - FETCH_WORKERS=10
      - MINIMUM_SECONDS_RECHECK_TIME=3
      - ALLOW_FILE_URI=False
      - DISABLE_VERSION_CHECK=true
      - TZ=America/Los_Angeles

    ports:
      - 5000:5000
    restart: unless-stopped

    depends_on:
      browser-chrome:
        condition: service_started
      sockpuppetbrowser:
        condition: service_started

  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome:4
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

volumes:
  changedetection-data:
